apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  namespace: counter-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
      - name: counter-service
        image: ${ECR_REGISTRY}/counter-service:${IMAGE_TAG}
        ports:
        - containerPort: 443
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"