apiVersion: v1
kind: Service
metadata:
  name: counter-service
  namespace: counter-service
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: counter-service